### ISSUE TITLE
Please check you aren't installing a "tests" module

### ISSUE THREAD

**Issue by gordonwatts** [iris-hep/ast-language#7]
Your find_packages doesn't either explicitly say what sub-dirs to look at or remove "tests" from consideration. As a result I suspect you are installing tests in the root site packages directory with the wheel built from the setup.py.

To test this, just print out the result of find_packages() - it should be just the ast-language directory.

**Comment by masonproffitt** [comment]
Ah, good catch. `find_packages()` doesn't care about the `__init__.py` thing, but it will pick up any directory with Python files if it's not explicitly ignored.

**Comment by gordonwatts** [comment]
I learned this the hard way...

Cheers,
Gordon

________________________________
